### ISSUE TITLE
Is list<string> a typo, synonym for array or type I can't find docs on?

### ISSUE THREAD

**Issue by leonstafford** [szepeviktor/small-project#12]
ie in https://github.com/szepeviktor/small-project/blob/346d4c3008a2fc67f47df19a5b54c9546a27f135/src/Requirements.php#L69

```php
    /**
     * @param list<string> $plugins
     */
    public function plugins(array $plugins): self
    ```

**Comment by szepeviktor** [comment]
It is a WIP in PHPStan.
`list<x>` equals `array<int, x>`

**Comment by leonstafford** [comment]
Awesome, thanks as always for educating me :)
